Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles_app.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.sign_up, name='signup'),
    path('Login/', views.UserLogin, name='login'),
    path('Logout/', views.UserLogout, name='logout'),
]

articles_app/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

app_name = 'articles_app'
urlpatterns = [
    path('', views.Articles, name="Home"),
    path('create', views.Create, name="create"),
    path('<slug>', views.Articles_detail, name="detail"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Articles(models.Model):
    title = models.CharField(max_length=64)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='default.jpg', blank=True)
    author = models.ForeignKey(User,default=None, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:60] + ' .....'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class SignupForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        
        model=User
        fields=('username','email','password')

    def clean(self):
        cleaned_data = super(SignupForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

class LoginForm(forms.Form):
    username = forms.CharField(max_length=32)
    password = forms.CharField(max_length=16)

articles_app/forms.py
from django import forms
from .models import Articles


class CreateArticles(forms.ModelForm):

    class Meta:
        model = Articles
        exclude = ['date','author']

Blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

accounts/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm , LoginForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


def sign_up(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create_user(
            cd['username'], cd['email'], cd['password'],)
            user.save()
            messages.success(request, 'User Register Successfully', 'success')
            return redirect('articles_app:Home')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


def UserLogin(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(
                    request, 'User logged Successfully', 'success')
                return redirect('articles_app:Home')
            else:
                messages.error(
                    request, 'username or password is wrong', 'danger')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


def UserLogout(request):
    logout(request)
    return redirect('articles_app:Home')

articles_app/views.py
from datetime import date
from django.shortcuts import render, redirect
from . import models
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from . import forms


def Articles(request):
    articles = models.Articles.objects.all().order_by('-date')
    art = articles
    return render(request, 'articles.html', {'art': art})


@login_required(login_url='accounts:login')
def Articles_detail(request, slug):
    article = models.Articles.objects.get(slug=slug)
    return render(request, 'articles_detail.html', {'article': article})


@login_required(login_url='accounts:login')
def Create(request):
    if request.method == 'POST':
        form = forms.CreateArticles(request.POST, request.FILES)
        if form.is_valid():
            inst= form.save(commit=False)
            inst.author = request.user
            inst.save()
            return redirect('articles_app:Home')
    else:
        form = forms.CreateArticles()
    return render(request, 'create.html', {'form': form})

templates/articles.html
    {%extends 'base.html'%}


    {% block content %}
    
    <p></p><h1>Article List</h1></p>
    {% for i in art %}
    <h2><a href="{% url 'articles_app:detail' slug=i.slug %}">{{i.title}}</a></h2>
    <p>{{i.snippet}}</p>
    <p>{{i.date}}</p>
    {% endfor %}
    {% endblock content%}

templates/articles_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="articles-detail">
    <div class="article">
        <img src="{{article.image.url}}" alt="">
        <h1>{{article.title}}</h1>
        <p>{{article.body}}</p>
        <h4>added by {{article.author}}</h4>
        <small>{{article.date}}</small>



    </div>


</div>



{%endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <title>weblog</title>
        <link rel="stylesheet" href="{% static 'styles.css'%}"></head>


    <body>
        
        <nav>
            <h1><a href="{% url 'articles_app:Home' %}">Home</a></h1>
            
            


        </nav>
        <nav>
            <ul>
                {% if user.is_authenticated %}

                <h1 >
                    Welcome {{ user.get_username }}
                </h1><br>

               

                <button><a href="{% url 'accounts:logout' %}">logout</a></button>

                

                <a href="{% url 'articles_app:create'%}">Create New Article</a>
                {% else %}
                <li>
                    <a href="{% url 'accounts:login'%}">Login</a>
                </li>
                <li>
                    <a href="{% url 'accounts:signup'%}">Signup</a>
                </li>

                {% endif %}

            </ul>
        </nav>

        {%block content%}
        {%endblock%}
    </body>

</html>

templates/create.html
{% extends 'base.html' %}
{% block content %}
<h1>Create</h1>
<h3>
    <form class="site-form" action="{% url 'articles_app:create' %}"
        method="post" enctype="multipart/form-data">
        {{form}}
        {% csrf_token %}
        <input type="submit" name="" value="Create">
    </form>
</h3>
{%endblock%}

templates/login.html
{%extends 'base.html'%}


{% block content %}
<h1>Login</h1>
<form action="{% url 'accounts:login' %}" method="post">
    {{ form }}
    {% csrf_token %}
    {%if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">

    {%endif%}

    <input type="submit" value="Login">
</form>
{% endblock content%}

templates/signup.html
{%extends 'base.html'%}


{% block content %}
<h1>SignUp</h1>
<form action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Signup">
</form>
{% endblock content%}